org: gsterndale
app: bftp-edgar
service: bftp-edgar
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    EDGAR_UA: ${env:EDGAR_UA}
    EDGAR_RATE_LIMIT: ${env:EDGAR_RATE_LIMIT}
    GOOGLE_SPREADSHEET_ID: ${env:GOOGLE_SPREADSHEET_ID}
    GOOGLE_SERVICE_ACCOUNT_EMAIL: ${env:GOOGLE_SERVICE_ACCOUNT_EMAIL}
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${env:GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY}

functions:
  ciksHandler:
    handler: index.findCIKs
    events:
      - schedule: rate(30 days)

  filingsHandler:
    handler: index.findFilings
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-plugin-typescript
