name: Query EDGAR for filings by CIKs

on:
  workflow_dispatch:
    inputs:
      cik:
        description: "CIK list"
        default: ""
        required: true
        type: string

jobs:
  query-edgar:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ""
          check-latest: false
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Query EDGAR
        env:
          EDGAR_UA: ${{ secrets.EDGAR_UA }}
        run: npm run filings "${{ inputs.cik }}" filings.csv
      - name: Archive filing results
        uses: actions/upload-artifact@v3
        with:
          name: filings
          path: filings.csv
