name: Manually run filings

on:
  workflow_dispatch:
    inputs:
      cik:
        description: "CIK list"
        default: ""
        required: true
        type: string

jobs:
  filngs:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Output CIKs
        run: echo "${{ inputs.ciks }}"
      - name: Query EDGAR
        run: npm run filings "${{ inputs.cik }}" filings.csv
      - name: Archive filing results
        uses: actions/upload-artifact@v3
        with:
          name: filings
          path: filings.csv
