name: Manually run filings

on:
  workflow_dispatch:
    inputs:
      companies:
        description: "Companies.csv content"
        default: ""
        required: true
        type: string

jobs:
  filngs:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Write CSV to file
        run: echo "${{ inputs.companies }}" > companies.csv
      - name: Query EDGAR
        run: head companies.csv > filings.csv
      - name: Archive filing results
        uses: actions/upload-artifact@v3
        with:
          name: filings
          path: filings.csv
